[default]
path   = "/"
color  = "#31AF31"

[index]
path   = "/index/"
prefix = "i."
emoji  = "ğŸ—„"
color  = "#F0C61F"

[entities]
path = "/entities/"
emoji = "ğŸ”‘"

[Ontologies]
path = "/ontologies"
emoji = "ğŸ“‚"

[Surveys]
path = "/surveys"
emoji = "ğŸ“‚"